- name: create folder {{ blackbox_exporter_container_name }}
  ansible.builtin.file:
    path: "{{ blackbox_exporter_docker_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: copy template blackbox exporter config to {{ blackbox_exporter_docker_dir }}
  ansible.builtin.copy:
    src: "files/blackbox.yaml"
    dest: "{{ blackbox_exporter_docker_dir }}/blackbox.yaml"
    group: "{{ username }}"
    owner: "{{ username }}"

- name: Copy template docker-compose to {{ blackbox_exporter_dir }}
  ansible.builtin.template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ blackbox_exporter_docker_dir }}/docker-compose.yaml"
    group: "{{ username }}"
    owner: "{{ username }}" 

- name: start blackbox exporter
  community.docker.docker_compose_v2:
    project_src: "{{ blackbox_exporter_docker_dir }}" 
    recreate: always
    state: present